// v0.9.5 — every Gen I move the game uses, at its Gen I name and its modern type where that type exists in the game
// (Gust Flying, Karate Chop Fighting, Sand Attack Ground; Bite stays Normal — there is no Dark). Columns:
// [id, type, range M|R, AP, power, opts]. opts: mod sf|sb, tgt cleave, eff [...], crit, igdef, cd.
const st = (status, chance, extra = {}) => ({ kind: 'status', status, chance, ...extra });
const sg = (target, stat, stages) => ({ kind: 'stage', target, stat, stages });
const heal = (p, durationTurns) => ({ kind: 'heal', percentOfMaxHp: p, ...(durationTurns ? { durationTurns } : {}) });
const drain = (p) => ({ kind: 'drain', percentOfDamage: p });
const recoil = (p) => ({ kind: 'recoil', percentOfDamage: p });
const mh = (hits) => ({ kind: 'multi-hit', hits });
const draw = (cards) => ({ kind: 'draw', cards });
export const E = { st, sg, heal, drain, recoil, mh, draw };

export const MOVES = [
  ['pound', 'normal', 'M', 1, 40],
  // Gen I's high-critical moves crit every time here (alwaysCrit), and pay for it at the foot of their band.
  ['karate-chop', 'fighting', 'M', 1, 40, { crit: true }],
  ['double-slap', 'normal', 'M', 1, 45, { eff: [mh(3)] }],
  ['comet-punch', 'normal', 'M', 1, 45, { eff: [mh(3)] }],
  ['mega-punch', 'normal', 'M', 2, 75],
  ['pay-day', 'normal', 'R', 1, 50],
  ['fire-punch', 'fire', 'M', 2, 70, { eff: [st('burn', 0.1)] }],
  ['ice-punch', 'ice', 'M', 2, 70, { eff: [st('freeze', 0.1)] }],
  ['thunder-punch', 'electric', 'M', 2, 70, { eff: [st('paralysis', 0.1)] }],
  ['scratch', 'normal', 'M', 1, 40],
  ['vice-grip', 'normal', 'M', 1, 50],
  ['guillotine', 'normal', 'M', 4, 130, { igdef: true, cd: 2 }],
  // §4.3.4 Backstrike — the whirlwind that reaches past the Lead to a declared bench slot, and fizzles if it is empty.
  ['razor-wind', 'normal', 'R', 3, 95, { tgt: 'backstrike' }],
  ['swords-dance', 'normal', 'U', 1, 0, { eff: [sg('self', 'attack', 2)] }],
  ['cut', 'normal', 'M', 1, 50],
  ['gust', 'flying', 'R', 1, 45],
  ['wing-attack', 'flying', 'M', 2, 65],
  ['whirlwind', 'normal', 'U', 0, 0, { eff: [draw(1)] }],
  ['fly', 'flying', 'M', 3, 90, { mod: 'sf' }],
  ['bind', 'normal', 'M', 1, 40, { eff: [sg('foe', 'defense', -1)] }],
  ['slam', 'normal', 'M', 2, 75],
  ['vine-whip', 'grass', 'R', 1, 45],
  ['stomp', 'normal', 'M', 2, 70],
  ['double-kick', 'fighting', 'M', 1, 50, { eff: [mh(2)] }],
  ['mega-kick', 'normal', 'M', 4, 120],
  ['jump-kick', 'fighting', 'M', 2, 65, { mod: 'sf', eff: [recoil(0.2)] }],
  ['rolling-kick', 'fighting', 'M', 2, 65, { mod: 'sb' }],
  ['sand-attack', 'ground', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'attack', -1)] }],
  ['headbutt', 'normal', 'M', 2, 70],
  ['horn-attack', 'normal', 'M', 2, 65],
  ['fury-attack', 'normal', 'M', 1, 45, { eff: [mh(3)] }],
  ['horn-drill', 'normal', 'M', 4, 130, { igdef: true, cd: 2 }],
  ['tackle', 'normal', 'M', 1, 40],
  ['body-slam', 'normal', 'M', 3, 85, { eff: [st('paralysis', 0.3)] }],
  ['wrap', 'normal', 'M', 1, 40, { eff: [sg('foe', 'defense', -1)] }],
  ['take-down', 'normal', 'M', 2, 75, { eff: [recoil(0.25)] }],
  ['thrash', 'normal', 'M', 3, 100, { eff: [st('confusion', 1, { self: true })] }],
  ['double-edge', 'normal', 'M', 4, 120, { eff: [recoil(0.33)] }],
  ['tail-whip', 'normal', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'defense', -1)] }],
  ['poison-sting', 'poison', 'R', 1, 45, { eff: [st('poison', 0.3)] }],
  ['twineedle', 'bug', 'R', 2, 70, { eff: [mh(2), st('poison', 0.2)] }],
  ['pin-missile', 'bug', 'R', 2, 75, { eff: [mh(3)] }],
  ['leer', 'normal', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'defense', -1)] }],
  ['bite', 'normal', 'M', 1, 50],
  ['growl', 'normal', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'attack', -1)] }],
  ['roar', 'normal', 'U', 1, 0, { range: 'R', eff: [sg('foe', 'attack', -1), sg('foe', 'defense', -1)] }],
  ['sing', 'normal', 'U', 1, 0, { range: 'R', eff: [st('sleep', 0.55)] }],
  ['supersonic', 'normal', 'U', 1, 0, { range: 'R', eff: [st('confusion', 0.55)] }],
  ['sonic-boom', 'normal', 'R', 1, 50],
  ['disable', 'normal', 'U', 1, 0, { range: 'R', eff: [sg('foe', 'attack', -2)] }],
  ['acid', 'poison', 'R', 1, 45, { eff: [sg('foe', 'defense', -1)] }],
  ['ember', 'fire', 'R', 1, 45, { eff: [st('burn', 0.1)] }],
  ['flamethrower', 'fire', 'R', 3, 95, { eff: [st('burn', 0.1)] }],
  ['mist', 'ice', 'U', 1, 0, { eff: [{ kind: 'team-guard', guard: 'status' }] }],
  ['water-gun', 'water', 'R', 1, 45],
  ['hydro-pump', 'water', 'R', 4, 120],
  ['surf', 'water', 'R', 2, 70, { tgt: 'cleave' }],
  ['ice-beam', 'ice', 'R', 3, 95, { eff: [st('freeze', 0.1)] }],
  ['blizzard', 'ice', 'R', 4, 120, { eff: [st('freeze', 0.1)] }],
  ['psybeam', 'psychic', 'R', 2, 70, { eff: [st('confusion', 0.1)] }],
  ['bubble-beam', 'water', 'R', 2, 65, { eff: [sg('foe', 'attack', -1)] }],
  ['aurora-beam', 'ice', 'R', 2, 65, { eff: [sg('foe', 'attack', -1)] }],
  ['hyper-beam', 'normal', 'R', 4, 130, { cd: 2 }],
  ['peck', 'flying', 'M', 1, 45],
  ['drill-peck', 'flying', 'M', 2, 75],
  ['submission', 'fighting', 'M', 3, 90, { eff: [recoil(0.25)] }],
  ['low-kick', 'fighting', 'M', 1, 50],
  ['counter', 'fighting', 'M', 2, 65, { eff: [{ kind: 'power-bonus', when: 'self-below', below: 0.5, multiplier: 1.5 }] }],
  ['seismic-toss', 'fighting', 'M', 2, 70],
  ['strength', 'normal', 'M', 2, 75],
  ['absorb', 'grass', 'R', 1, 45, { eff: [drain(0.5)] }],
  ['mega-drain', 'grass', 'R', 2, 70, { eff: [drain(0.5)] }],
  ['leech-seed', 'grass', 'U', 1, 0, { range: 'R', eff: [st('poison', 0.9)] }],
  ['growth', 'normal', 'U', 0, 0, { eff: [sg('self', 'attack', 1)] }],
  ['razor-leaf', 'grass', 'R', 2, 65, { crit: true }],
  ['solar-beam', 'grass', 'R', 4, 120, { cd: 1 }],
  ['poison-powder', 'poison', 'U', 1, 0, { range: 'R', eff: [st('poison', 0.75)] }],
  ['stun-spore', 'grass', 'U', 1, 0, { range: 'R', eff: [st('paralysis', 0.75)] }],
  ['sleep-powder', 'grass', 'U', 1, 0, { range: 'R', eff: [st('sleep', 0.75)] }],
  ['petal-dance', 'grass', 'M', 3, 100, { mod: 'sf', eff: [st('confusion', 1, { self: true })] }],
  ['string-shot', 'bug', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'defense', -1)] }],
  ['dragon-rage', 'dragon', 'R', 1, 50],
  ['fire-spin', 'fire', 'R', 2, 65, { eff: [st('burn', 0.3)] }],
  ['thunder-shock', 'electric', 'R', 1, 45, { eff: [st('paralysis', 0.1)] }],
  ['thunderbolt', 'electric', 'R', 3, 95, { eff: [st('paralysis', 0.1)] }],
  ['thunder-wave', 'electric', 'U', 1, 0, { range: 'R', eff: [st('paralysis', 1)] }],
  ['thunder', 'electric', 'R', 4, 120, { eff: [st('paralysis', 0.1)] }],
  ['rock-throw', 'rock', 'R', 1, 50],
  ['earthquake', 'ground', 'M', 3, 90, { tgt: 'cleave', cd: 1 }],
  ['fissure', 'ground', 'M', 4, 130, { igdef: true, cd: 2 }],
  ['dig', 'ground', 'M', 2, 75, { mod: 'sb' }],
  ['toxic', 'poison', 'U', 1, 0, { range: 'R', eff: [st('poison', 0.85, { escalating: true })] }],
  ['confusion', 'psychic', 'R', 1, 50, { eff: [st('confusion', 0.1)] }],
  ['psychic', 'psychic', 'R', 3, 95],
  ['hypnosis', 'psychic', 'U', 1, 0, { range: 'R', eff: [st('sleep', 0.6)] }],
  ['meditate', 'psychic', 'U', 0, 0, { eff: [sg('self', 'attack', 1)] }],
  ['agility', 'psychic', 'U', 0, 0, { eff: [sg('self', 'attack', 1), draw(1)] }],
  ['quick-attack', 'normal', 'M', 1, 40, { mod: 'sf' }],
  ['rage', 'normal', 'M', 1, 40, { eff: [sg('self', 'attack', 1)] }],
  ['teleport', 'psychic', 'U', 0, 0, { eff: [draw(1)] }],
  ['night-shade', 'ghost', 'R', 2, 70],
  ['screech', 'normal', 'U', 1, 0, { range: 'R', eff: [sg('foe', 'defense', -2)] }],
  ['double-team', 'normal', 'U', 0, 0, { eff: [sg('self', 'defense', 1)] }],
  ['recover', 'normal', 'U', 1, 0, { cd: 2, eff: [heal(0.4)] }],
  ['harden', 'normal', 'U', 0, 0, { eff: [sg('self', 'defense', 1)] }],
  ['minimize', 'normal', 'U', 1, 0, { eff: [sg('self', 'defense', 2)] }],
  ['smokescreen', 'normal', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'attack', -1)] }],
  ['confuse-ray', 'ghost', 'U', 1, 0, { range: 'R', eff: [st('confusion', 1)] }],
  ['withdraw', 'water', 'U', 0, 0, { eff: [sg('self', 'defense', 1)] }],
  ['defense-curl', 'normal', 'U', 0, 0, { eff: [sg('self', 'defense', 1)] }],
  ['barrier', 'psychic', 'U', 1, 0, { eff: [sg('self', 'defense', 2)] }],
  ['light-screen', 'psychic', 'U', 1, 0, { eff: [{ kind: 'team-guard', guard: 'cleave', percent: 50 }] }],
  ['haze', 'ice', 'U', 1, 0, { range: 'R', eff: [{ kind: 'team-cure' }] }],
  ['reflect', 'psychic', 'U', 1, 0, { eff: [sg('self', 'defense', 1), sg('bench', 'defense', 1)] }],
  ['focus-energy', 'normal', 'U', 0, 0, { eff: [sg('self', 'attack', 1)] }],
  ['metronome', 'normal', 'U', 1, 0, { eff: [draw(2)] }],
  ['mirror-move', 'flying', 'U', 1, 0, { eff: [sg('self', 'attack', 1), draw(1)] }],
  ['self-destruct', 'normal', 'M', 3, 130, { eff: [recoil(0.5)] }],
  ['egg-bomb', 'normal', 'R', 3, 95],
  ['lick', 'ghost', 'M', 1, 40, { eff: [st('paralysis', 0.3)] }],
  ['smog', 'poison', 'R', 1, 45, { eff: [st('poison', 0.4)] }],
  ['sludge', 'poison', 'R', 2, 70, { eff: [st('poison', 0.3)] }],
  ['bone-club', 'ground', 'M', 2, 65],
  ['fire-blast', 'fire', 'R', 4, 120, { eff: [st('burn', 0.3)] }],
  ['waterfall', 'water', 'M', 2, 75],
  ['clamp', 'water', 'M', 1, 45, { eff: [sg('foe', 'defense', -1)] }],
  ['swift', 'normal', 'R', 1, 55],
  ['skull-bash', 'normal', 'M', 3, 95],
  ['spike-cannon', 'normal', 'R', 1, 50, { eff: [mh(3)] }],
  ['constrict', 'normal', 'M', 1, 40, { eff: [sg('foe', 'defense', -1)] }],
  ['amnesia', 'psychic', 'U', 1, 0, { eff: [sg('self', 'defense', 2)] }],
  ['kinesis', 'psychic', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'attack', -1)] }],
  ['soft-boiled', 'normal', 'U', 1, 0, { cd: 2, eff: [heal(0.5)] }],
  ['high-jump-kick', 'fighting', 'M', 3, 100, { mod: 'sf', eff: [recoil(0.25)] }],
  ['glare', 'normal', 'U', 1, 0, { range: 'R', eff: [st('paralysis', 0.75)] }],
  ['dream-eater', 'psychic', 'R', 2, 90, { eff: [drain(0.5)] }],
  ['poison-gas', 'poison', 'U', 1, 0, { range: 'R', eff: [st('poison', 0.55)] }],
  ['barrage', 'normal', 'R', 1, 50, { eff: [mh(3)] }],
  ['leech-life', 'bug', 'M', 1, 45, { eff: [drain(0.5)] }],
  ['lovely-kiss', 'normal', 'U', 1, 0, { range: 'R', eff: [st('sleep', 0.75)] }],
  ['sky-attack', 'flying', 'M', 4, 110, { mod: 'sf', crit: true, cd: 1 }],
  ['transform', 'normal', 'U', 1, 0, { eff: [sg('self', 'attack', 1), sg('self', 'defense', 1)] }],
  ['bubble', 'water', 'R', 1, 45, { eff: [sg('foe', 'attack', -1)] }],
  ['dizzy-punch', 'normal', 'M', 2, 65, { eff: [st('confusion', 0.2)] }],
  ['spore', 'grass', 'U', 2, 0, { range: 'R', eff: [st('sleep', 1)] }],
  ['flash', 'normal', 'U', 0, 0, { range: 'R', eff: [sg('foe', 'attack', -1)] }],
  ['psywave', 'psychic', 'R', 1, 50],
  ['splash', 'normal', 'U', 0, 0, { eff: [draw(1)] }],
  ['acid-armor', 'poison', 'U', 1, 0, { eff: [sg('self', 'defense', 3)] }],
  ['crabhammer', 'water', 'M', 3, 85, { crit: true }],
  ['explosion', 'normal', 'M', 4, 170, { cd: 2, eff: [recoil(0.75)] }],
  ['fury-swipes', 'normal', 'M', 1, 45, { eff: [mh(3)] }],
  ['bonemerang', 'ground', 'R', 2, 70, { eff: [mh(2)] }],
  ['rest', 'psychic', 'U', 1, 0, { eff: [heal(1), st('sleep', 1, { self: true })] }],
  ['rock-slide', 'rock', 'R', 2, 75],
  ['hyper-fang', 'normal', 'M', 2, 75],
  ['sharpen', 'normal', 'U', 0, 0, { eff: [sg('self', 'attack', 1)] }],
  ['conversion', 'normal', 'U', 1, 0, { eff: [sg('self', 'attack', 1), sg('self', 'defense', 1)] }],
  ['tri-attack', 'normal', 'R', 3, 90, { eff: [st('burn', 0.07), st('paralysis', 0.07), st('freeze', 0.07)] }],
  ['super-fang', 'normal', 'M', 2, 1, { eff: [{ kind: 'fixed-damage', percentOfTargetHp: 0.5 }] }],
  ['slash', 'normal', 'M', 2, 60, { crit: true }],
];

/** A + whose derived numbers are not what its card should be. */
export const PLUS_OVERRIDES = {};
